### ISSUE TITLE
Where is the recommended place for a .swiftlint.yml

### ISSUE THREAD

**Issue by regnerjr** [norio-nomura/ExtraBuildPhase#3]
I have tried `~` home directory and project directory, neither seem to work?

**Comment by norio-nomura** [comment]
I use `~/.swiftlint.yml` with following option:

``` sh
% defaults write io.github.norio-nomura.ExtraBuildPhase shellScript -string '
if which swiftlint >/dev/null; then
    swiftlint lint --use-script-input-files --config ~/.swiftlint.yml 2>/dev/null
fi
exit 0 # ignore result of swiftlint
'
```

**Comment by jonasman** [comment]
Can the .swiftlint.yml be read from the project folder by default? That is the best way to do it

**Comment by norio-nomura** [comment]
@jonasman You can use build settings environment variables in `shellScript` such as:

``` sh
% defaults write io.github.norio-nomura.ExtraBuildPhase shellScript -string '
if which swiftlint >/dev/null; then
    swiftlint lint --use-script-input-files --config $SRCROOT/.swiftlint.yml 2>/dev/null
fi
exit 0 # ignore result of swiftlint
'
```

IIRC, build phase script is executed with project folder as current directory. So it should work without `--config` arguments in `shellScript`.

**Comment by jonasman** [comment]
At least with me i cannot make the lint to ignore pods folder when used with this plugin. Manual adding the run script works fine

**Comment by norio-nomura** [comment]
ExtraBuildPhase inserts build phase into **every target**. On building targets in Pods might have different `SRCROOT`.

**Comment by jonasman** [comment]
Ha ok!

Hm then it is a no go for me
